name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install speed-docs
        run: npm install -g speed-docs

      - name: Deploy to GitHub Pages
        uses: ./apps/speed-docs-github-action
        with:
          content-path: "./test-content"
          github-token: ${{ secrets.GITHUB_TOKEN }}
