name: Auto-Update Action Version

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update package.json version
        run: |
          cd apps/speed-docs-github-action

          # Update package.json with the release version
          npm version ${{ steps.version.outputs.version }} --no-git-tag-version

          echo "Updated package.json to version ${{ steps.version.outputs.version }}"

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add apps/speed-docs-github-action/package.json
          git commit -m "chore: auto-update action version to ${{ steps.version.outputs.version }} [skip ci]"
          git push

      - name: Verify version sync
        run: |
          cd apps/speed-docs-github-action
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          EXPECTED_VERSION="${{ steps.version.outputs.version }}"

          if [ "$CURRENT_VERSION" = "$EXPECTED_VERSION" ]; then
            echo "✅ Version sync successful: $CURRENT_VERSION"
          else
            echo "❌ Version sync failed: expected $EXPECTED_VERSION, got $CURRENT_VERSION"
            exit 1
          fi
