name: Deploy Documentation

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        id: setup_pages
        uses: actions/configure-pages@v5

      - name: Deploy docs to GitHub Pages
        uses: nicnocquee/speed-docs-github-action@v1
        with:
          content-path: "./docs"
          base-path: ${{ steps.setup_pages.outputs.base_path }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
